import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Counter from "../components/Counter"
import dynamic from "next/dynamic"

const DisplayCounter = dynamic(() => import("secondary/displayCounter"));

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        minHeight: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center'

      }}>
        <div
          style={{
            backgroundColor: 'lightblue',
            minHeight: '700px',
            height: '700px',
            width: '40%',
            paddingTop: '30%',
            padding: '20px',
            alignItems: 'center',
            justifyContent: 'center'
          }}>
          <h2>
            Primary App
          </h2>
          <div>
            <Counter />
          </div>
        </div>
        <div>
          <DisplayCounter />
        </div>
      </div>
    </div>
  )
}
