import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from "../components/Footer"
import Nav from "../components/Nav"
import Counter from "../components/Counter"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav>This is my nav from main app 1</Nav>
      <main className={styles.main}>
        <div>
          <Counter />
        </div>
      </main>
      <Footer />
    </div>
  )
}
